# Generated by Django 5.2.7 on 2025-11-11 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre')),
                ('usuario', models.CharField(max_length=50, verbose_name='usuario')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('passw', models.CharField(max_length=80, verbose_name='passw')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha inscripcion')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen')),
            ],
        ),
    ]
