# Generated by Django 5.2.8 on 2026-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='Admin', max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Profesor', 'Profesor')], default='Usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(default='admin', max_length=50, unique=True),
        ),
    ]
