# Generated by Django 5.2.8 on 2025-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_email_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Profesor', 'Profesor')], default='', verbose_name='tipo_usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(verbose_name='edad'),
        ),
    ]
