# Generated by Django 5.2.8 on 2025-12-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_tipo_alter_usuario_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Profesor', 'Profesor')], default='', max_length=20, verbose_name='tipo_usuario'),
        ),
    ]
