# Generated by Django 5.2.8 on 2025-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='capacidad_max',
            field=models.IntegerField(default='0', verbose_name='capacidad_max'),
        ),
    ]
