# Generated by Django 5.2.8 on 2025-12-09 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clase_capacidad_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='dia',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
