# Generated by Django 5.2.8 on 2026-02-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_clase_dia_clase_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, verbose_name='Día')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('capacidad_max', models.PositiveIntegerField(default=0, verbose_name='Capacidad máxima')),
            ],
            options={
                'verbose_name': 'Horario de clase',
                'verbose_name_plural': 'Horarios de clases',
                'ordering': ['dia', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='TipoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, unique=True, verbose_name='Nombre de la clase')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de clase',
                'verbose_name_plural': 'Tipos de clases',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.AddField(
            model_name='horarioclase',
            name='tipo_clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clases.tipoclase', verbose_name='Tipo de clase'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioclase',
            unique_together={('tipo_clase', 'dia', 'hora')},
        ),
    ]
